### ISSUE TITLE
播放路径问题

### ISSUE THREAD

**Issue by jijacky** [wy3/media-server#4]
工具 ：OBS/VLC
结果 ：

推流地址 rtmp://127.0.0.1/a/b
拉流地址 rtmp://127.0.0.1/a/b
失败

推流地址 rtmp://127.0.0.1/a/b
拉流地址 rtmp://127.0.0.1/ab
成功

其他拉流地址均失败

**Comment by wy3** [comment]
没有复现出这种情况

**Comment by jijacky** [comment]
![新建OpenDocument 绘图](https://github.com/wy3/media-server/assets/38582997/b9625b3e-1834-4ef3-bba6-4699439ff71e)
php版本7.4.3。这是我这里的截图。ab或者z/b/可以播放，但是a/b不行。

**Comment by jijacky** [comment]
> ![新建OpenDocument 绘图](https://private-user-images.githubusercontent.com/38582997/340174417-b9625b3e-1834-4ef3-bba6-4699439ff71e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDkxMjksIm5iZiI6MTcxODYwODgyOSwicGF0aCI6Ii8zODU4Mjk5Ny8zNDAxNzQ0MTctYjk2MjViM2UtMTgzNC00ZWYzLWJiYTYtNDY5OTQzOWZmNzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA3MjAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMjg0NDJkZTdmMzljMjNkYjIwOGFlYmI3NTc1ODM3MmI0OGY4OTAyNGRlY2NlMTEwNWQwY2RmODJkNjZmY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sdasRN_Pf6Er2l6iC8PYdUHI5F1trA5nZHVYKrg_KdY) php版本7.4.3。这是我这里的截图。ab或者z/b/可以播放，但是a/b不行。

已经解决，是应为使用obs时，/a/b中的b需要放置在推流码里面，这样就可以使用/a/b路径播放了。但是全部放置于服务器，推流码为空时，就是上面的问题
